import mongoose from "mongoose";
import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";

const userSchema = new mongoose.Schema(
    {
        username : {
            type : String,
            required : [true, "Username is required"],
            unique : [true, "Username already exists"],
            trim : true,
            minLength : [3, "Username must be at least 3 characters long"],
            maxLength : [30, "Username must be at most 30 characters long"],
            lowercase : true,
            index: true,
            //if u want to maake a database very optimized and fast , then we can use index on the fields which are used for searching and filtering .
            // so just make index true on the fields which are used for searching and filtering .
        },
        email : {
            type : String,
            required : [true, "Username is required"],
            unique : [true, "Username already exists"],
            lowercase : true,
            trim : true,
        },
        fullname : {
            type : String,
            required : [true, "Fullname is required"],
            trim : true,
            minLength : [3, "Fullname must be at least 3 characters long"],
            maxLength : [100, "Fullname must be at most 100 characters long"],
            index: true,
        },
        avatar : {
            type : String,
            //cloudinary url of the image which is uploaded by the user , if user has not uploaded any image then we will use a default image url which is present in cloudinary.
            required : true, 
    },
        coverImage : {
            type : String,
            //cloudinary url of the image which is uploaded by the user , if user has not uploaded any image then we will use a default image url which is present in cloudinary.
            default : "https://res.cloudinary.com/dxjv0qg5f/image/upload/v1690911681/coverImage/default_coverImage_2_ozkq3r.png",
        },
        watchHistory : {
            type : mongoose.Schema.Types.ObjectId,
            ref : "Video",
            default : null,
        },
        password : {
            type : String,
            required : [true, "Password is required"], 
        },
        refreshToken : {
            type : String,
            default : null,
        }
    },
    {
        timestamps : true,
    }
);

//Used to hash the password before saving it to the database. This is a security measure to protect user passwords in case of a data breach.
//The pre-save hook is a middleware function that is executed before the save() method is called on a document. In this case, it checks if the password field has been modified, and if so, it hashes the password using bcrypt before saving it to the database.
userSchema.pre("save", async function(next){
    if(!this.isModified("password")) return next();

    this.password = await bcrypt.hash(this.password, 10); //It is the number of rounds to use when generating a salt. The higher the number,
    // the more secure the hash will be, but it will also take longer to generate. A value of 10 is a good balance between security and performance.
    next();
});

// This method is generated by us compare the password entered by the user with the hashed password stored in the database. It uses bcrypt's compare function to compare the two passwords and returns a boolean value indicating whether they match or not.
//userSchema.methods.methodName = function(){...} is used to define instance methods for a Mongoose model. Instance methods are functions that can be called on individual documents (instances) of the model. In this case, comparePassword is an instance method that can be called on a User document to compare a given password with the hashed password stored in the database.

userSchema.methods.comparePassword = async function(password){
    return await bcrypt.compare(password, this.password);
}

userSchema.methods.generateAccessToken = function(){
    return jwt.sign(
        {
            _id : this._id,
            email : this.email,
            username : this.username,
            fullname : this.fullname,
        },
        process.env.ACCESS_TOKEN_SECRET,
        {
            expiresIn : process.env.ACCESS_TOKEN_EXPIRATION,
        }
    );
}

userSchema.methods.generateRefreshToken = function(){
    return jwt.sign(
        {
            _id : this._id,
        },
        process.env.REFRESH_TOKEN_SECRET,
        {
            expiresIn : process.env.REFRESH_TOKEN_EXPIRATION,
        }
    );
}